from datetime import datetime


def generate_report(filename, analysis, migration_plan):
    report = []

    report.append("=" * 60)
    report.append("        QuantumShield-X Security Report")
    report.append("=" * 60)

    report.append(f"Project : {filename}")
    report.append(f"Generated On : {datetime.now()}")
    report.append("")

    report.append("=" * 60)
    report.append("Quantum Risk Analysis")
    report.append("=" * 60)

    for file_data in analysis:

        report.append(f"\nFile : {file_data['file']}")

        for algo in file_data["algorithms"]:

            report.append(f"""
Algorithm      : {algo['name']}
Risk Level     : {algo['risk']}
Recommendation : {algo['recommendation']}
""")

    report.append("\n")
    report.append("=" * 60)
    report.append("Migration Plan")
    report.append("=" * 60)

    for file_data in migration_plan:

        report.append(f"\nFile : {file_data['file']}")

        for migration in file_data["migrations"]:

            report.append(f"""
Algorithm       : {migration['algorithm']}
Replace With    : {migration['replace_with']}
Difficulty      : {migration['difficulty']}
Estimated Time  : {migration['estimated_time']}
Reason          : {migration['why']}
Sample Code     : {migration['sample_code']}
""")

    report.append("\n")
    report.append("=" * 60)
    report.append("Generated by QuantumShield-X")
    report.append("=" * 60)

    return "\n".join(report)