import "./AIRecommendation.css";

import Navbar from "../components/Navbar/Navbar";

import {

    MdAutoAwesome,

    MdPsychology,

    MdCheckCircle,

    MdArrowForward

} from "react-icons/md";

function AIRecommendation(){

    return(

        <>

            <Navbar/>

            <main className="recommendation-page">

                <section className="recommendation-header">

                    <h1>

                        AI Recommendation Engine

                    </h1>

                    <p>

                        Intelligent Post-Quantum Cryptography migration recommendations generated by QuantumShield-X AI.

                    </p>

                </section>

                <section className="recommendation-card">

                    <div className="recommendation-top">

                        <div className="recommendation-icon">

                            <MdAutoAwesome/>

                        </div>

                        <div>

                            <h2>

                                AI Migration Recommendation

                            </h2>

                            <p>

                                Based on project analysis, QuantumShield-X recommends replacing vulnerable cryptographic algorithms with NIST-approved Post Quantum Cryptography standards.

                            </p>

                        </div>

                    </div>

                    <div className="recommendation-grid">

                        <div className="recommend-box">

                            <MdPsychology className="recommend-icon"/>

                            <div>

                                <h3>

                                    Replace RSA

                                </h3>

                                <p>

                                    ML-KEM (CRYSTALS-Kyber)

                                </p>

                            </div>

                        </div>

                        <div className="recommend-box">

                            <MdPsychology className="recommend-icon"/>

                            <div>

                                <h3>

                                    Replace ECDSA

                                </h3>

                                <p>

                                    ML-DSA (Dilithium)

                                </p>

                            </div>

                        </div>
                                                <div className="recommend-box">

                            <MdCheckCircle className="recommend-icon success"/>

                            <div>

                                <h3>

                                    Migration Priority

                                </h3>

                                <p>

                                    High

                                </p>

                            </div>

                        </div>

                        <div className="recommend-box">

                            <MdArrowForward className="recommend-icon"/>

                            <div>

                                <h3>

                                    Estimated Time

                                </h3>

                                <p>

                                    3 - 5 Days

                                </p>

                            </div>

                        </div>

                    </div>

                    <div className="ai-analysis">

                        <h2>

                            AI Explanation

                        </h2>

                        <p>

                            QuantumShield-X AI analyzed the uploaded project and found RSA-2048 and ECDSA implementations. These algorithms are vulnerable to quantum attacks using Shor's Algorithm. The AI recommends migrating to ML-KEM (CRYSTALS-Kyber) for key encapsulation and ML-DSA (Dilithium) for digital signatures. This migration will significantly improve long-term cryptographic security.

                        </p>

                    </div>

                    <div className="recommend-summary">

                        <div className="summary-card">

                            <h3>

                                AI Confidence

                            </h3>

                            <h1>

                                98%

                            </h1>

                        </div>

                        <div className="summary-card">

                            <h3>

                                Compatibility

                            </h3>

                            <h1>

                                High

                            </h1>

                        </div>
                                                <div className="summary-card">

                            <h3>

                                Migration Difficulty

                            </h3>

                            <h1>

                                Medium

                            </h1>

                        </div>

                    </div>

                    <div className="next-step">

                        <button className="next-btn">

                            Continue to Migration Planner

                            <MdArrowForward/>

                        </button>

                    </div>

                </section>

            </main>

        </>

    );

}

export default AIRecommendation;