import "./AIRecommendation.css";

import { useState, useEffect } from "react";

import Navbar from "../components/Navbar/Navbar";

import {
    MdAutoAwesome,
    MdPsychology,
    MdCheckCircle,
    MdArrowForward
} from "react-icons/md";

function AIRecommendation() {

    const [recommendations, setRecommendations] = useState([]);

    useEffect(() => {

        fetch("http://127.0.0.1:8000/recommendation/")

            .then((res) => res.json())

            .then((data) => {

                setRecommendations(data);

            })

            .catch((err) => {

                console.log(err);

            });

    }, []);

    return (

        <>

            <Navbar />

            <main className="recommendation-page">

                <section className="recommendation-header">

                    <h1>

                        AI Recommendation Engine

                    </h1>

                    <p>

                        Intelligent Post-Quantum Cryptography migration recommendations generated by QuantumShield-X AI.

                    </p>

                </section>

                <section className="recommendation-card">

                    <div className="recommendation-top">

                        <div className="recommendation-icon">

                            <MdAutoAwesome />

                        </div>

                        <div>

                            <h2>

                                AI Migration Recommendation

                            </h2>

                            <p>

                                Based on project analysis, QuantumShield-X recommends replacing vulnerable cryptographic algorithms with NIST-approved Post Quantum Cryptography standards.

                            </p>

                        </div>

                    </div>

                    <div className="recommendation-grid">

                        {

                            recommendations.length > 0 ?

                                recommendations.map((item, index) => (

                                    <div
                                        className="recommend-box"
                                        key={index}
                                    >

                                        <MdPsychology className="recommend-icon" />

                                        <div>

                                            <h3>

                                                Replace {item.algorithm}

                                            </h3>

                                            <p>

                                                {item.replace_with}

                                            </p>

                                            <small>

                                                Priority : {item.priority}

                                            </small>

                                        </div>

                                    </div>

                                ))

                                :

                                <p>No recommendations available.</p>

                        }

                    </div>

                    <div className="ai-analysis">

                        <h2>

                            AI Explanation

                        </h2>

                        <p>

                            QuantumShield-X AI analyzed the uploaded project and generated migration recommendations based on the detected cryptographic algorithms. The recommendations follow NIST Post-Quantum Cryptography standards.

                        </p>

                    </div>

                    <div className="recommend-summary">

                        <div className="summary-card">

                            <h3>

                                AI Confidence

                            </h3>

                            <h1>

                                98%

                            </h1>

                        </div>

                        <div className="summary-card">

                            <h3>

                                Compatibility

                            </h3>

                            <h1>

                                High

                            </h1>

                        </div>

                        <div className="summary-card">

                            <h3>

                                Migration Difficulty

                            </h3>

                            <h1>

                                Medium

                            </h1>

                        </div>

                    </div>

                    <div className="next-step">

                        <button className="next-btn">

                            Continue to Migration Planner

                            <MdArrowForward />

                        </button>

                    </div>

                </section>

            </main>

        </>

    );

}

export default AIRecommendation;