import "./RiskReport.css";

import Navbar from "../components/Navbar/Navbar";

import {

    MdDescription,

    MdSecurity,

    MdWarning,

    MdCheckCircle,

    MdDownload

} from "react-icons/md";

function RiskReport(){

    return(

        <>

            <Navbar/>

            <main className="report-page">

                <section className="report-header">

                    <h1>

                        Quantum Security Report

                    </h1>

                    <p>

                        Comprehensive AI-generated security assessment and migration report.

                    </p>

                </section>

                <section className="report-card">

                    <div className="report-top">

                        <div className="report-icon">

                            <MdDescription/>

                        </div>

                        <div>

                            <h2>

                                Project Security Summary

                            </h2>

                            <p>

                                This report summarizes cryptographic vulnerabilities, AI recommendations and post-quantum migration status generated by QuantumShield-X.

                            </p>

                        </div>

                    </div>

                    <div className="report-grid">

                        <div className="report-item">

                            <MdSecurity className="report-item-icon"/>

                            <div>

                                <h3>

                                    Overall Risk Score

                                </h3>

                                <p>

                                    74% (Medium Risk)

                                </p>

                            </div>

                        </div>

                        <div className="report-item">

                            <MdWarning className="report-item-icon warning"/>

                            <div>

                                <h3>

                                    Vulnerable Algorithms

                                </h3>

                                <p>

                                    12 Algorithms

                                </p>

                            </div>

                        </div>

                        <div className="report-item">

                            <MdCheckCircle className="report-item-icon success"/>

                            <div>

                                <h3>

                                    PQC Ready

                                </h3>

                                <p>

                                    61%

                                </p>

                            </div>

                        </div>

                        <div className="report-item">

                            <MdDownload className="report-item-icon"/>

                            <div>

                                <h3>

                                    Report Status

                                </h3>

                                <p>

                                    Ready to Export

                                </p>

                            </div>

                        </div>

                    </div>
                                        <div className="report-analysis">

                        <h2>

                            AI Security Findings

                        </h2>

                        <p>

                            QuantumShield-X AI identified multiple cryptographic implementations that are vulnerable to future quantum attacks. RSA-2048 and ECDSA are recommended for immediate migration to ML-KEM (CRYSTALS-Kyber) and ML-DSA (Dilithium). The AI also verified that AES-256 implementations remain quantum-resistant for symmetric encryption.

                        </p>

                    </div>

                    <div className="report-summary">

                        <div className="summary-card">

                            <h3>

                                Critical Findings

                            </h3>

                            <h1>

                                8

                            </h1>

                        </div>

                        <div className="summary-card">

                            <h3>

                                Migration Progress

                            </h3>

                            <h1>

                                41%

                            </h1>

                        </div>

                        <div className="summary-card">

                            <h3>

                                AI Confidence

                            </h3>

                            <h1>

                                98%

                            </h1>

                        </div>

                    </div>

                    <div className="migration-report">

                        <h2>

                            Migration Recommendation

                        </h2>

                        <table className="report-table">

                            <thead>

                                <tr>

                                    <th>

                                        Current Algorithm

                                    </th>

                                    <th>

                                        Recommended PQC

                                    </th>

                                    <th>

                                        Priority

                                    </th>

                                </tr>

                            </thead>

                            <tbody>

                                <tr>

                                    <td>

                                        RSA-2048

                                    </td>

                                    <td>

                                        ML-KEM (CRYSTALS-Kyber)

                                    </td>

                                    <td>

                                        High

                                    </td>

                                </tr>

                                <tr>

                                    <td>

                                        ECDSA

                                    </td>

                                    <td>

                                        ML-DSA (Dilithium)

                                    </td>

                                    <td>

                                        High

                                    </td>

                                </tr>

                                <tr>

                                    <td>

                                        SHA-256

                                    </td>

                                    <td>

                                        No Migration Required

                                    </td>

                                    <td>

                                        Low

                                    </td>

                                </tr>

                            </tbody>

                        </table>

                    </div>
                                        <div className="report-footer">

                        <button className="download-btn">

                            <MdDownload/>

                            Download PDF Report

                        </button>

                    </div>

                </section>

            </main>

        </>

    );

}

export default RiskReport;